### PR TITLE
roulettemons

### PR DESCRIPTION
**Pull request by PSwan19**
add roulettemons sprites

### CODE REVIEW

**Comment by monsanto** [comment]
It is unclear at this moment if pet mods will be tracked by this repository. However, even if we did, I couldn't accept your PR as-is because the minisprites are not trimmed. Please give your upload to whoever you're working with on the rest of the code.

**Comment by charizard8888** [comment]
Can you explain us what do you mean by trimming the minisprites so that can be fixed?

**Comment by monsanto** [comment]
Your minisprites (as well as your full-sized sprites, I just didn't look at them before commenting) have superfluous transparent padding around the actual content. In some cases, [the sprite is not centered in the image](https://raw.githubusercontent.com/petuuuhhh/pokemon-sprites/c43872a37bdd7de2ee557d7af371e6996e9834fc/src/noncanonical/sprites/petmods/icons/toados.png), so trimming this padding would lead to information loss. It's unclear if the off-center sprites are intentional.

In addition, files in this repository are named in accordance to their entries in `pokedex.js`, using the naming scheme in the README of this repository. Please browse around for examples.

Like I said though, it's unclear if we will accept pet mods into this repository. If you are insistent on these sprites being apart of this repository (and therefore partially maintained by our staff), I will need to know more about what you're doing.
- Are these new Pokemon intended to be added to `pokedex.js` in PS upstream? Are they for a side server? If the answer is side server, this repository is not the home for your work; @scheibo had some thoughts about secondary repositories, maybe he has some input here.
- If the answer to the first question is 'added upstream', is this mod a long-term project? Do you have a community to maintain it, similar to the Smogon Create-A-Pokemon project?

**Comment by scoopapa** [comment]
> Are these new Pokemon intended to be added to pokedex.js in PS upstream?

Yes, currently in progress: smogon/pokemon-showdown#6579

> is this mod a long-term project?

It's the Pet Mod of the Season, so it will have a ladder on the main PS server for the next 3 months.

> Do you have a community to maintain it, similar to the Smogon Create-A-Pokemon project?

Yes, although the project is essentially done, except for small balance changes or possibly the addition of a mega to an unviable pokemon: 
[https://www.smogon.com/forums/threads/roulettemons-pet-mod-of-the-season.3649106/page-23#post-8433902](url)

**Comment by Zarel** [comment]
Note that they're going in `data/mods/roulettemons/pokedex.js`, not `data/pokedex.js`.

My plan is to have a separate mod directory for their sprites on PS; they're certainly not being mixed into the regular list like CAPs are.

**Pull request closed without merging**
