### PR TITLE
Requested updates

### PR DESCRIPTION
**Pull request by rjd1922**
I replaced Glameow's modern models with the Generation 7 versions which fixed the shape of its ears, and moved shiny Original Color Magearna's dex image to the proper name. There are other issues like the Unown letters besides A missing sprites from before Gen 5, Pangogo's shiny Gen 5 animated sprites being its normal colors, and Castform's normal form shiny sprite from Gen 3 being identical to its normal color sprite, but I don't know how to fix those.

### CODE REVIEW

**Comment by rjd1922** [comment]
Also added missing Shiny Icy Snow Pattern Vivillon and Marshadow Dex sprites, and replaced Ultra Necrozma April Fool's Day Shiny sprites.

**Comment by rjd1922** [comment]
**Please** fix these already. Added some changes from this forum thread: https://www.smogon.com/forums/threads/ps-model-mod-fixing-thread.3500358/page-26

Fixed choppy Mega Steelix ring animation.
Made Aipom and Ambipom have consistent animation speed across genders (thanks to Mia on the Smogon forums).
Removed stray blue pixels in top right of Archeops's animation (courtesy of DrPumpkinz).
Added missing shiny female Snover back.
Uploaded shiny Popplio Dex sprite; it's not used in Showdown because it's misnamed (https://play.pokemonshowdown.com/sprites/dex-shiny/poppolio.png)

**Comment by monsanto** [comment]
Sorry for being unresponsive! I happened to see your last comment on our Discord feed of GH activity. This project isn't primarily developed on GitHub, and also, it's kind of an alpha-quality deal that isn't in a place to take outside contributions. The way this usually goes is that people send fixes to me or Marty and we handle optimizing the sprites & adding them to the repo + a couple of other tasks. It's alright if other people commit too I guess, but you'd want to coordinate with us on Discord (where we primarily talk about art-related stuff). If you aren't familiar with the Discord channel it is #art on https://spo.ink/dev

I can update the README with a warning about this

**Comment by monsanto** [comment]
I asked Marty to take a look at this and hopefully we can get all of this sorted out.

**Comment by Marty-D** [comment]
@rjd1922 Hi, apologies for the late reply. It doesn't appear that you've joined the dev Discord linked above to discuss these changes so I'll leave my thoughts here.

The Vivillon, Popplio, and Marshadow dex sprites need to be trimmed preserving displacement from center, like the rest. Since you copy+pasted the Magearna sprites from this repo, those are fine. Everything else just needs to be optimized. Regarding Steelix, the palette needs to be optimized as well. Most "model" sprites have a colour count of ~16 to make them look uniform and the file size reasonable, but these new Steelix sprites have hundreds of colours (and even though the debris loop is better the body loop is worse).

If you keep the afd and Magearna changes and remove everything else then this can be merged, and I'll deal with the others myself. I appreciate the effort either way. 👍 

Something else to keep in mind - Showdown doesn't pull from this repo in any way at the moment and the same changes may not appear there any time soon.

**Comment by rjd1922** [comment]
I fixed the crop on the Vivillon, Popplio, and Marshadow dex sprites. I'm a total noob and can't figure out how to get rid of the other changes without manually deleting the new files and uploading the old ones.

**Comment by Marty-D** [comment]
Fixed in https://github.com/smogon/sprites/commit/5e8d12d0f1602bea369ef8a6b8d06e4400878469, thanks again!

**Pull request closed without merging**
